### ISSUE TITLE
配置列表没有查询出结果

### ISSUE THREAD

**Issue by sunbao** [dph5199278/nacos#1]
启动可以，新建一个配置文件也入库了，但是查询没有数据，是不是查询语句的问题？

**Comment by dph5199278** [comment]
这边是没有问题的
可能是你那边操作上的问题：
1. 选的命名空间不对
2. 查询方式不对，参照下面来：
空值查询表示列出当前命名空间的全部配置
带值查询表示列出当前命名空间等于这个值的配置
带值查询中，想要模糊查询带上*号，*可以简单理解为数据库中的%

**Comment by dph5199278** [comment]
先关闭此Issue，如有问题再重开。
