### ISSUE TITLE
登录报用户名密码错误

### ISSUE THREAD

**Issue by p0mp0k0** [dph5199278/nacos#2]
登录报用户名密码错误
![image](https://user-images.githubusercontent.com/11995019/194750492-55bcc479-ab33-4282-a2a4-4762a03119d7.png)

**Comment by dph5199278** [comment]
默认用户名密码：nacos/nacos
不行的话，直接参照官方重置密码：
[地址](https://nacos.io/zh-cn/docs/console-guide.html)
